name: JisrAlLawziyah
options:
  bundleIdPrefix: com.lexq
targets:
  JisrAlLawziyah:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "جسر اللوزية"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
